version: "3.8"
services:
    db:
        image: mysql:5.7
        container_name: '${APP_NAME}-db'
        restart: always
        ports:
            - '${DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
          - db:/var/lib/mysql
          - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
        healthcheck:
          test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
          interval: 5s
          retries: 5
        env_file:
            - ./.env
    
    app:
        container_name: php-apache
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
            - phpmyadmin
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8000:80

    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin1
      restart: always
      ports:
        - '8081:80'
      environment:
        PMA_HOST: db

volumes:
  db:
  .: